# Created using wingetcreate

PackageIdentifier: PrusaResearch.PrusaSlicer
PackageVersion: 2.3.1
Installers:
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://cdn.prusa3d.com/downloads/drivers/PrusaSlicer_Win_standalone_2.3.1.exe#_ga=2.9956275.706234789.1622198027-11425403.1622198027
  InstallerSha256: 38D1AEF8E8EC30E2C064B4AF24DAB6DF43468E0ABD2AC934A77A7F1243A4AC62
ManifestType: installer
ManifestVersion: 1.0.0
